# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lw_battleAfterWarning = QtWidgets.QListWidget(self.groupBox_5)
        self.lw_battleAfterWarning.setObjectName("lw_battleAfterWarning")
        self.verticalLayout_5.addWidget(self.lw_battleAfterWarning)
        self.gridLayout.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lw_wait = QtWidgets.QListWidget(self.groupBox)
        self.lw_wait.setObjectName("lw_wait")
        self.verticalLayout.addWidget(self.lw_wait)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lw_battleWarning = QtWidgets.QListWidget(self.groupBox_2)
        self.lw_battleWarning.setObjectName("lw_battleWarning")
        self.verticalLayout_2.addWidget(self.lw_battleWarning)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lw_battle = QtWidgets.QListWidget(self.groupBox_3)
        self.lw_battle.setObjectName("lw_battle")
        self.verticalLayout_3.addWidget(self.lw_battle)
        self.gridLayout.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lw_battleWait = QtWidgets.QListWidget(self.groupBox_4)
        self.lw_battleWait.setObjectName("lw_battleWait")
        self.verticalLayout_4.addWidget(self.lw_battleWait)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listWidget_7 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_7.setObjectName("listWidget_7")
        self.verticalLayout_7.addWidget(self.listWidget_7)
        self.gridLayout.addWidget(self.groupBox_6, 2, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_baudRate = QtWidgets.QComboBox(self.groupBox_7)
        self.cb_baudRate.setObjectName("cb_baudRate")
        self.gridLayout_2.addWidget(self.cb_baudRate, 0, 1, 1, 1)
        self.pb_open = QtWidgets.QPushButton(self.groupBox_7)
        self.pb_open.setObjectName("pb_open")
        self.gridLayout_2.addWidget(self.pb_open, 0, 2, 1, 1)
        self.cb_comport = QtWidgets.QComboBox(self.groupBox_7)
        self.cb_comport.setObjectName("cb_comport")
        self.gridLayout_2.addWidget(self.cb_comport, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "전투 완료 후 경고"))
        self.groupBox.setTitle(_translate("MainWindow", "대기화면"))
        self.groupBox_2.setTitle(_translate("MainWindow", "전투 진입 전 경고"))
        self.groupBox_3.setTitle(_translate("MainWindow", "전투 진입"))
        self.groupBox_4.setTitle(_translate("MainWindow", "전투 대기"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_7.setTitle(_translate("MainWindow", "시리얼"))
        self.pb_open.setText(_translate("MainWindow", "Open"))
