# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        self.le_txCommand = QtWidgets.QLineEdit(self.frame)
        self.le_txCommand.setObjectName("le_txCommand")
        self.gridLayout.addWidget(self.le_txCommand, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.le_PORT = QtWidgets.QLineEdit(self.groupBox)
        self.le_PORT.setObjectName("le_PORT")
        self.gridLayout_2.addWidget(self.le_PORT, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.cb_PORT = QtWidgets.QComboBox(self.groupBox)
        self.cb_PORT.setObjectName("cb_PORT")
        self.gridLayout_2.addWidget(self.cb_PORT, 0, 1, 1, 1)
        self.pb_Open = QtWidgets.QPushButton(self.groupBox)
        self.pb_Open.setObjectName("pb_Open")
        self.gridLayout_2.addWidget(self.pb_Open, 0, 2, 1, 1)
        self.le_IP = QtWidgets.QLineEdit(self.groupBox)
        self.le_IP.setObjectName("le_IP")
        self.gridLayout_2.addWidget(self.le_IP, 1, 1, 1, 1)
        self.pb_Connect = QtWidgets.QPushButton(self.groupBox)
        self.pb_Connect.setObjectName("pb_Connect")
        self.gridLayout_2.addWidget(self.pb_Connect, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "PORT"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.pb_Open.setText(_translate("MainWindow", "PushButton"))
        self.pb_Connect.setText(_translate("MainWindow", "PushButton"))
        self.label_3.setText(_translate("MainWindow", "COM"))
